/**
 * The built-in slash command catalog: every `/command` the composer offers
 * regardless of provider, with its aliases and one-line description. Data
 * only, so the submit path can consult it without loading the menu.
 */

import { type BetterC0deShareMode } from "@/lib/betterc0de-share-policy"
import { BETTERC0DE_INPUT_ACTION_COMMANDS } from "@/lib/betterc0de-keybinds"

export interface SlashCommand {
  id: string
  name: string
  aliases?: string[]
  description: string
  category: "provider" | "project" | "skill" | "builtin"
  action: "insert" | "execute"
  /** Native token to insert when the menu uses a different display prefix. */
  insertText?: string
}

export const GOAL_SUBCOMMANDS: SlashCommand[] = [
  {
    id: "goal-pause",
    name: "/goal pause",
    description: "Pause the goal and stop its current turn",
    category: "builtin",
    action: "insert",
  },
  {
    id: "goal-continue",
    name: "/goal continue",
    aliases: ["/goal resume"],
    description: "Continue the goal with the selected model and permissions",
    category: "builtin",
    action: "insert",
  },
  {
    id: "goal-status",
    name: "/goal status",
    description: "Show the current goal and its progress",
    category: "builtin",
    action: "insert",
  },
  {
    id: "goal-edit",
    name: "/goal edit",
    description: "Change the objective · /goal edit <goal text>",
    category: "builtin",
    action: "insert",
  },
  {
    id: "goal-clear",
    name: "/goal clear",
    description: "Stop and remove the current goal",
    category: "builtin",
    action: "insert",
  },
  {
    id: "goal-set",
    name: "/goal set",
    description: "Start a new goal · /goal set <goal text>",
    category: "builtin",
    action: "insert",
  },
]

export const BUILTIN_COMMANDS: SlashCommand[] = [
  {
    id: "goal",
    name: "/goal",
    description: "Start a goal with the selected model · /goal <goal text>",
    category: "builtin",
    action: "insert",
  },
  ...GOAL_SUBCOMMANDS,
  {
    id: "model",
    name: "/model",
    aliases: [
      "/models",
      "/model.choose",
      "/model.list",
      "/model-list",
      "/v2.model.list",
      "/v2-model-list",
    ],
    description: "Open the model picker",
    category: "builtin",
    action: "execute",
  },
  {
    id: "command-palette",
    name: "/command-palette",
    aliases: ["/command.palette.show", "/command-palette-show"],
    description: "Open the command palette",
    category: "builtin",
    action: "execute",
  },
  {
    id: "model-next",
    name: "/model-next",
    aliases: ["/next-model", "/model-cycle", "/model.cycle_recent"],
    description: "Cycle to the next configured model",
    category: "builtin",
    action: "execute",
  },
  {
    id: "model-previous",
    name: "/model-previous",
    aliases: ["/previous-model", "/prev-model", "/model.cycle_recent_reverse"],
    description: "Cycle to the previous configured model",
    category: "builtin",
    action: "execute",
  },
  {
    id: "favorite-next",
    name: "/favorite-next",
    aliases: [
      "/next-favorite",
      "/favorite-model-next",
      "/model.cycle_favorite",
    ],
    description: "Cycle to the next favorite model",
    category: "builtin",
    action: "execute",
  },
  {
    id: "favorite-toggle",
    name: "/favorite-toggle",
    aliases: ["/model.dialog.favorite", "/model-dialog-favorite"],
    description: "Toggle the current model as a favorite",
    category: "builtin",
    action: "execute",
  },
  {
    id: "favorite-previous",
    name: "/favorite-previous",
    aliases: [
      "/previous-favorite",
      "/prev-favorite",
      "/favorite-model-previous",
      "/model.cycle_favorite_reverse",
    ],
    description: "Cycle to the previous favorite model",
    category: "builtin",
    action: "execute",
  },
  {
    id: "sessions",
    name: "/sessions",
    aliases: [
      "/session",
      "/resume",
      "/continue",
      "/session.list",
      "/session.get",
      "/session-list",
      "/v2.session.list",
      "/v2-session-list",
      "/session.next",
      "/session.previous",
      "/session.next.unseen",
      "/session.previous.unseen",
    ],
    description: "List recent chats and resume one by id",
    category: "builtin",
    action: "execute",
  },
  {
    id: "session-status",
    name: "/session-status",
    aliases: ["/session.status", "/status.session", "/thread-status"],
    description: "Show BetterC0de status for the active chat session",
    category: "builtin",
    action: "execute",
  },
  {
    id: "new",
    name: "/new",
    aliases: ["/clear", "/session.new", "/session.create", "/session-new"],
    description: "Start a new chat session",
    category: "builtin",
    action: "execute",
  },
  {
    id: "init",
    name: "/init",
    aliases: ["/session.init"],
    description: "Create or update AGENTS.md for this workspace",
    category: "builtin",
    action: "execute",
  },
  {
    id: "review",
    name: "/review",
    description: "Review uncommitted changes, a commit, branch, or PR",
    category: "builtin",
    action: "execute",
  },
  {
    id: "pr",
    name: "/pr",
    aliases: ["/pull-request", "/gh-pr", "/github.pr", "/github-pr"],
    description: "Review a GitHub PR using BetterC0de PR targeting",
    category: "builtin",
    action: "execute",
  },
  {
    id: "github-agent",
    name: "/github",
    aliases: [
      "/github-agent",
      "/github.install",
      "/github-install",
      "/github.run",
      "/github-run",
    ],
    description: "Show or create BetterC0de GitHub agent workflow",
    category: "builtin",
    action: "execute",
  },
  {
    id: "review-toggle",
    name: "/review-toggle",
    aliases: ["/review.toggle", "/review-panel-toggle"],
    description: "Toggle the review/diff panel",
    category: "builtin",
    action: "execute",
  },
  {
    id: "commands",
    name: "/commands",
    aliases: ["/project-commands", "/command.list", "/command-list"],
    description: "List or write repo-local BetterC0de commands",
    category: "builtin",
    action: "execute",
  },
  {
    id: "undo",
    name: "/undo",
    aliases: ["/session.undo", "/session.revert"],
    description: "Restore the previous chat/filesystem checkpoint",
    category: "builtin",
    action: "execute",
  },
  {
    id: "redo",
    name: "/redo",
    aliases: ["/session.redo", "/session.unrevert"],
    description: "Reapply the last checkpoint undo",
    category: "builtin",
    action: "execute",
  },
  {
    id: "interrupt",
    name: "/interrupt",
    aliases: ["/stop", "/cancel", "/session.interrupt", "/session.abort"],
    description: "Interrupt the active provider turn",
    category: "builtin",
    action: "execute",
  },
  {
    id: "fork",
    name: "/fork",
    aliases: ["/session.fork"],
    description: "Fork this chat into an independent session",
    category: "builtin",
    action: "execute",
  },
  {
    id: "parent",
    name: "/parent",
    aliases: ["/session-parent", "/session.parent"],
    description: "Jump from a forked chat back to its parent session",
    category: "builtin",
    action: "execute",
  },
  {
    id: "child",
    name: "/child",
    aliases: [
      "/children",
      "/session-child",
      "/session.child",
      "/session.children",
      "/session.child.first",
    ],
    description: "Jump to this chat's latest child fork",
    category: "builtin",
    action: "execute",
  },
  {
    id: "child-next",
    name: "/child-next",
    aliases: ["/next-child", "/session.child.next"],
    description: "Jump to the next sibling child session",
    category: "builtin",
    action: "execute",
  },
  {
    id: "child-previous",
    name: "/child-previous",
    aliases: ["/prev-child", "/previous-child", "/session.child.previous"],
    description: "Jump to the previous sibling child session",
    category: "builtin",
    action: "execute",
  },
  {
    id: "pin",
    name: "/pin",
    aliases: ["/pin-session", "/session.pin", "/session.pin.toggle"],
    description: "Pin or unpin the active chat session",
    category: "builtin",
    action: "execute",
  },
  {
    id: "pins",
    name: "/pins",
    aliases: ["/pinned", "/pinned-sessions"],
    description: "List pinned chat sessions",
    category: "builtin",
    action: "execute",
  },
  {
    id: "quick-switch",
    name: "/quick-switch",
    aliases: [
      "/session.quick_switch.1",
      "/session.quick_switch.2",
      "/session.quick_switch.3",
      "/session.quick_switch.4",
      "/session.quick_switch.5",
      "/session.quick_switch.6",
      "/session.quick_switch.7",
      "/session.quick_switch.8",
      "/session.quick_switch.9",
    ],
    description: "Switch to a pinned session slot",
    category: "builtin",
    action: "execute",
  },
  {
    id: "delete-session",
    name: "/delete-session",
    aliases: ["/delete", "/session.delete"],
    description: "Delete a chat session after confirmation",
    category: "builtin",
    action: "execute",
  },
  {
    id: "archive-session",
    name: "/archive",
    aliases: ["/archive-session", "/session.archive"],
    description: "Archive a chat session",
    category: "builtin",
    action: "execute",
  },
  {
    id: "unarchive-session",
    name: "/unarchive",
    aliases: ["/unarchive-session", "/session.unarchive"],
    description: "Restore an archived chat session",
    category: "builtin",
    action: "execute",
  },
  {
    id: "archives",
    name: "/archives",
    aliases: ["/archived", "/archived-sessions"],
    description: "List archived chat sessions",
    category: "builtin",
    action: "execute",
  },
  {
    id: "share",
    name: "/share",
    aliases: ["/session.share"],
    description: "Copy a local markdown export for this chat",
    category: "builtin",
    action: "execute",
  },
  {
    id: "unshare",
    name: "/unshare",
    aliases: ["/session.unshare"],
    description: "Remove this chat's local share marker",
    category: "builtin",
    action: "execute",
  },
  {
    id: "copy",
    name: "/copy",
    aliases: ["/session.copy"],
    description: "Copy this chat transcript to the clipboard",
    category: "builtin",
    action: "execute",
  },
  {
    id: "copy-last",
    name: "/copy-last",
    aliases: ["/copy-assistant", "/copy-message", "/messages.copy"],
    description: "Copy the latest assistant message to the clipboard",
    category: "builtin",
    action: "execute",
  },
  {
    id: "export",
    name: "/export",
    aliases: ["/session.export", "/betterc0de-export", "/betterc0de.export"],
    description: "Export this chat transcript into the workspace",
    category: "builtin",
    action: "execute",
  },
  {
    id: "import",
    name: "/import",
    aliases: ["/session.import", "/betterc0de-import", "/betterc0de.import"],
    description: "Import a BetterC0de JSON session from a file or URL",
    category: "builtin",
    action: "execute",
  },
  {
    id: "diff",
    name: "/diff",
    aliases: ["/session.diff", "/diffs"],
    description: "Show the active chat session diff summary",
    category: "builtin",
    action: "execute",
  },
  {
    id: "rename",
    name: "/rename",
    aliases: ["/title", "/session.rename", "/session.update"],
    description: "Rename the active chat session",
    category: "builtin",
    action: "execute",
  },
  {
    id: "timeline",
    name: "/timeline",
    aliases: ["/session.timeline"],
    description: "Show a compact timeline of this chat session",
    category: "builtin",
    action: "execute",
  },
  {
    id: "events",
    name: "/events",
    aliases: ["/event.subscribe", "/event-subscribe", "/session.events"],
    description: "Show a BetterC0de event snapshot for this chat",
    category: "builtin",
    action: "execute",
  },
  {
    id: "messages",
    name: "/messages",
    aliases: [
      "/message-list",
      "/message",
      "/session.messages",
      "/session.message",
      "/session.message.list",
      "/v2.session.messages",
      "/v2-session-messages",
    ],
    description: "Page through messages in the active chat session",
    category: "builtin",
    action: "execute",
  },
  {
    id: "context",
    name: "/context",
    aliases: [
      "/session.context",
      "/context-list",
      "/v2.session.context",
      "/v2-session-context",
    ],
    description: "Inspect active chat context after the last compaction",
    category: "builtin",
    action: "execute",
  },
  {
    id: "history",
    name: "/history",
    aliases: ["/prompt-history", "/histories"],
    description: "List prompt history",
    category: "builtin",
    action: "execute",
  },
  {
    id: "history-use",
    name: "/history-use",
    aliases: [
      "/history-pop",
      "/prompt-history-use",
      "/prompt.history.previous",
      "/prompt-history-previous",
      "/prompt.history.next",
      "/prompt-history-next",
    ],
    description: "Restore a prompt history entry",
    category: "builtin",
    action: "execute",
  },
  {
    id: "prompt-clear",
    name: "/prompt-clear",
    aliases: ["/prompt.clear", "/clear-prompt"],
    description: "Clear the current composer prompt",
    category: "builtin",
    action: "execute",
  },
  {
    id: "prompt-paste",
    name: "/prompt-paste",
    aliases: ["/prompt.paste"],
    description: "Paste clipboard text into the composer prompt",
    category: "builtin",
    action: "execute",
  },
  {
    id: "prompt-submit",
    name: "/prompt-submit",
    aliases: ["/prompt.submit"],
    description: "BetterC0de prompt submit command reference",
    category: "builtin",
    action: "execute",
  },
  {
    id: "input-actions",
    name: "/input-actions",
    aliases: BETTERC0DE_INPUT_ACTION_COMMANDS.map((command) => `/${command}`),
    description: "Show BetterC0de composer input action handling",
    category: "builtin",
    action: "execute",
  },
  {
    id: "stash",
    name: "/stash",
    aliases: ["/prompt-stash", "/prompt.stash"],
    description: "Save prompt text to the prompt stash",
    category: "builtin",
    action: "execute",
  },
  {
    id: "stashes",
    name: "/stashes",
    aliases: ["/stash-list", "/prompt-stash-list", "/prompt.stash.list"],
    description: "List stashed prompts",
    category: "builtin",
    action: "execute",
  },
  {
    id: "stash-pop",
    name: "/stash-pop",
    aliases: ["/prompt-stash-pop", "/prompt.stash.pop"],
    description: "Restore and remove a stashed prompt",
    category: "builtin",
    action: "execute",
  },
  {
    id: "stash-delete",
    name: "/stash-delete",
    aliases: ["/stash-remove", "/prompt-stash-delete", "/stash.delete"],
    description: "Delete a stashed prompt",
    category: "builtin",
    action: "execute",
  },
  {
    id: "first-message",
    name: "/first",
    aliases: ["/first-message", "/messages.first", "/session.first"],
    description: "Scroll to the first chat message",
    category: "builtin",
    action: "execute",
  },
  {
    id: "last-message",
    name: "/last",
    aliases: ["/last-message", "/messages.last", "/session.last"],
    description: "Scroll to the last chat message",
    category: "builtin",
    action: "execute",
  },
  {
    id: "last-user-message",
    name: "/last-user",
    aliases: [
      "/last-user-message",
      "/messages-last-user",
      "/messages.last_user",
      "/session.messages_last_user",
    ],
    description: "Scroll to the latest user message",
    category: "builtin",
    action: "execute",
  },
  {
    id: "next-message",
    name: "/next-message",
    aliases: [
      "/message-next",
      "/message.next",
      "/messages.next",
      "/session.message.next",
    ],
    description: "Scroll to the next chat message",
    category: "builtin",
    action: "execute",
  },
  {
    id: "previous-message",
    name: "/previous-message",
    aliases: [
      "/prev-message",
      "/message-previous",
      "/message.previous",
      "/messages.previous",
      "/session.message.previous",
    ],
    description: "Scroll to the previous chat message",
    category: "builtin",
    action: "execute",
  },
  {
    id: "page-up",
    name: "/page-up",
    aliases: [
      "/pageup",
      "/messages-page-up",
      "/message.page_up",
      "/messages.page_up",
      "/session.page.up",
    ],
    description: "Scroll the chat transcript one page up",
    category: "builtin",
    action: "execute",
  },
  {
    id: "page-down",
    name: "/page-down",
    aliases: [
      "/pagedown",
      "/messages-page-down",
      "/message.page_down",
      "/messages.page_down",
      "/session.page.down",
    ],
    description: "Scroll the chat transcript one page down",
    category: "builtin",
    action: "execute",
  },
  {
    id: "line-up",
    name: "/line-up",
    aliases: [
      "/lineup",
      "/messages-line-up",
      "/message.line_up",
      "/messages.line_up",
      "/session.line.up",
    ],
    description: "Scroll the chat transcript one line up",
    category: "builtin",
    action: "execute",
  },
  {
    id: "line-down",
    name: "/line-down",
    aliases: [
      "/linedown",
      "/messages-line-down",
      "/message.line_down",
      "/messages.line_down",
      "/session.line.down",
    ],
    description: "Scroll the chat transcript one line down",
    category: "builtin",
    action: "execute",
  },
  {
    id: "half-page-up",
    name: "/half-page-up",
    aliases: ["/halfpage-up", "/session.half.page.up"],
    description: "Scroll the chat transcript half a page up",
    category: "builtin",
    action: "execute",
  },
  {
    id: "half-page-down",
    name: "/half-page-down",
    aliases: ["/halfpage-down", "/session.half.page.down"],
    description: "Scroll the chat transcript half a page down",
    category: "builtin",
    action: "execute",
  },
  {
    id: "open",
    name: "/open",
    aliases: ["/editor", "/file.open", "/prompt.editor", "/prompt-editor"],
    description: "Open Quick Open or a workspace file",
    category: "builtin",
    action: "execute",
  },
  {
    id: "editor-context-clear",
    name: "/editor-context-clear",
    aliases: ["/prompt.editor_context.clear", "/prompt-editor-context-clear"],
    description: "Clear active editor selection context",
    category: "builtin",
    action: "execute",
  },
  {
    id: "add-selection",
    name: "/add-selection",
    aliases: [
      "/context.addSelection",
      "/context-add-selection",
      "/selection-context",
    ],
    description: "Add the active editor selection to the composer context",
    category: "builtin",
    action: "execute",
  },
  {
    id: "close",
    name: "/close",
    aliases: ["/close-tab", "/tab.close"],
    description: "Close the active editor tab",
    category: "builtin",
    action: "execute",
  },
  {
    id: "file-tree-toggle",
    name: "/file-tree-toggle",
    aliases: [
      "/fileTree.toggle",
      "/filetree-toggle",
      "/file-tree.toggle",
      "/file-tree",
      "/files",
      "/files.toggle",
    ],
    description: "Toggle the workspace file tree",
    category: "builtin",
    action: "execute",
  },
  {
    id: "warp",
    name: "/warp",
    aliases: [
      "/workspace",
      "/workspace.set",
      "/workspace-set",
      "/project.open",
      "/project-open",
      "/project.update",
      "/project-update",
    ],
    description: "Change the workspace for this chat",
    category: "builtin",
    action: "execute",
  },
  {
    id: "project-next",
    name: "/project-next",
    aliases: ["/project.next"],
    description: "Switch to the next project represented by recent chats",
    category: "builtin",
    action: "execute",
  },
  {
    id: "project-previous",
    name: "/project-previous",
    aliases: ["/project.previous", "/project-prev"],
    description: "Switch to the previous project represented by recent chats",
    category: "builtin",
    action: "execute",
  },
  {
    id: "workspace-new",
    name: "/workspace-new",
    aliases: ["/workspace.new", "/worktree.create", "/worktree-create"],
    description: "Create an isolated git worktree for the active chat",
    category: "builtin",
    action: "execute",
  },
  {
    id: "workspace-toggle",
    name: "/workspace-toggle",
    aliases: [
      "/workspace.toggle",
      "/project.list",
      "/project-list",
      "/project.current",
      "/project-current",
    ],
    description: "Show workspace and worktree controls for this chat",
    category: "builtin",
    action: "execute",
  },
  {
    id: "workspace-list",
    name: "/workspace-list",
    aliases: ["/workspace.list", "/worktree-list", "/worktree.list"],
    description: "List git worktrees for the active workspace",
    category: "builtin",
    action: "execute",
  },
  {
    id: "workspace-remove",
    name: "/workspace-remove",
    aliases: ["/workspace.remove", "/worktree-remove", "/worktree.remove"],
    description: "Remove the isolated worktree for the active chat",
    category: "builtin",
    action: "execute",
  },
  {
    id: "workspace-reset",
    name: "/workspace-reset",
    aliases: ["/workspace.reset", "/worktree-reset", "/worktree.reset"],
    description: "Hard-reset the isolated worktree for the active chat",
    category: "builtin",
    action: "execute",
  },
  {
    id: "plan",
    name: "/plan",
    description: "Switch this thread into plan mode",
    category: "builtin",
    action: "execute",
  },
  {
    id: "ask",
    name: "/ask",
    description: "Switch this thread into read-only ask mode",
    category: "builtin",
    action: "execute",
  },
  {
    id: "default",
    name: "/default",
    aliases: ["/build", "/agent-mode"],
    description: "Return this thread to normal build mode",
    category: "builtin",
    action: "execute",
  },
  {
    id: "mode-next",
    name: "/chat-mode-next",
    aliases: ["/mode-next"],
    description: "Cycle to the next chat mode",
    category: "builtin",
    action: "execute",
  },
  {
    id: "mode-previous",
    name: "/chat-mode-previous",
    aliases: ["/mode-previous"],
    description: "Cycle to the previous chat mode",
    category: "builtin",
    action: "execute",
  },
  {
    id: "agent-next",
    name: "/agent",
    aliases: ["/agent-next", "/agent.cycle"],
    description: "Cycle to the next BetterC0de provider agent",
    category: "builtin",
    action: "execute",
  },
  {
    id: "agent-previous",
    name: "/agent-previous",
    aliases: ["/previous-agent", "/agent.cycle.reverse"],
    description: "Cycle to the previous BetterC0de provider agent",
    category: "builtin",
    action: "execute",
  },
  {
    id: "help",
    name: "/help",
    aliases: ["/help.show", "/help-show"],
    description: "Show all available commands",
    category: "builtin",
    action: "execute",
  },
  {
    id: "input-focus",
    name: "/input-focus",
    aliases: ["/input.focus", "/focus-input", "/composer-focus"],
    description: "Focus the chat input",
    category: "builtin",
    action: "execute",
  },
  {
    id: "exit",
    name: "/exit",
    aliases: ["/quit", "/q", "/app.exit", "/app-exit"],
    description: "Close the BetterC0de window",
    category: "builtin",
    action: "execute",
  },
  {
    id: "mcps",
    name: "/mcps",
    aliases: [
      "/mcp",
      "/mcp.list",
      "/mcp.ls",
      "/mcp.status",
      "/mcp-ls",
      "/mcps.ls",
    ],
    description: "List installed MCP servers",
    category: "builtin",
    action: "execute",
  },
  {
    id: "mcp-auth",
    name: "/mcp-auth",
    aliases: [
      "/mcp.auth",
      "/mcp.auth.list",
      "/mcp.auth.ls",
      "/mcp.auth.start",
      "/mcp.auth.callback",
      "/mcp.auth.authenticate",
      "/mcp-auth-list",
      "/mcp-auth-ls",
    ],
    description: "Show OAuth authentication status for MCP servers",
    category: "builtin",
    action: "execute",
  },
  {
    id: "mcp-add",
    name: "/mcp-add",
    aliases: ["/mcp.add", "/mcp-install", "/mcp.install"],
    description:
      "Open MCP setup or write BetterC0de MCP config with --config-only",
    category: "builtin",
    action: "execute",
  },
  {
    id: "mcp-logout",
    name: "/mcp-logout",
    aliases: ["/mcp.logout", "/mcp.auth.remove", "/mcp-auth-logout"],
    description: "Show MCP OAuth logout guidance",
    category: "builtin",
    action: "execute",
  },
  {
    id: "mcp-debug",
    name: "/mcp-debug",
    aliases: ["/mcp.debug", "/mcp-inspect"],
    description: "Inspect MCP connection/debug details",
    category: "builtin",
    action: "execute",
  },
  {
    id: "mcp-toggle",
    name: "/mcp-toggle",
    aliases: [
      "/toggle-mcp",
      "/mcp.toggle",
      "/mcp.connect",
      "/mcp.disconnect",
      "/dialog.mcp.toggle",
      "/dialog-mcp-toggle",
      "/mcp-enable",
      "/mcp-disable",
    ],
    description:
      "Enable or disable MCP server runtime state or config override",
    category: "builtin",
    action: "execute",
  },
  {
    id: "skills",
    name: "/skills",
    aliases: [
      "/prompt.skills",
      "/prompt-skills",
      "/debug.skill",
      "/debug-skill",
      "/app.skills",
    ],
    description: "List or add BetterC0de skill paths and URLs",
    category: "builtin",
    action: "execute",
  },
  {
    id: "agents",
    name: "/agents",
    aliases: [
      "/agent.list",
      "/agent-list",
      "/debug.agent",
      "/debug-agent",
      "/app.agents",
    ],
    description: "List subagents or show BetterC0de debug agent details",
    category: "builtin",
    action: "execute",
  },
  {
    id: "agent-create",
    name: "/agent-create",
    aliases: ["/agent.create", "/agents.create", "/create-agent"],
    description: "Show, write, or prefill BetterC0de agent creation",
    category: "builtin",
    action: "execute",
  },
  {
    id: "status",
    name: "/status",
    aliases: ["/betterc0de.status", "/betterc0de-status", "/global.health"],
    description: "Show provider and connection status",
    category: "builtin",
    action: "execute",
  },
  {
    id: "debug-info",
    name: "/debug-info",
    aliases: [
      "/debug.info",
      "/betterc0de.debug.info",
      "/betterc0de-debug-info",
    ],
    description: "Show BetterC0de app, OS, and runtime diagnostics",
    category: "builtin",
    action: "execute",
  },
  {
    id: "debug-paths",
    name: "/debug-paths",
    aliases: [
      "/debug.paths",
      "/betterc0de.debug.paths",
      "/betterc0de-debug-paths",
      "/db.path",
      "/db-path",
      "/paths",
      "/path.get",
      "/path-get",
    ],
    description: "Show BetterC0de data paths and SQLite database path",
    category: "builtin",
    action: "execute",
  },
  {
    id: "debug-rg",
    name: "/debug-rg",
    aliases: [
      "/debug.rg",
      "/debug.rg.files",
      "/debug.rg.search",
      "/debug.file",
      "/debug.file.read",
      "/debug-file-read",
      "/debug.file.list",
      "/debug-file-list",
      "/debug.file.status",
      "/debug-file-status",
      "/debug.file.search",
      "/debug.file.tree",
      "/file",
      "/file.read",
      "/file-read",
      "/file.list",
      "/file-list",
      "/file.status",
      "/file-status",
    ],
    description: "Run BetterC0de file status/list/read/search/tree diagnostics",
    category: "builtin",
    action: "execute",
  },
  {
    id: "find",
    name: "/find",
    aliases: [
      "/find.text",
      "/find-text",
      "/find.file",
      "/find-file",
      "/find.files",
      "/find-files",
      "/find.symbol",
      "/find-symbol",
      "/find.symbols",
      "/find-symbols",
    ],
    description: "Run BetterC0de find text/file/symbol search",
    category: "builtin",
    action: "execute",
  },
  {
    id: "debug-snapshot",
    name: "/debug-snapshot",
    aliases: [
      "/debug.snapshot",
      "/debug.snapshot.track",
      "/debug.snapshot.patch",
      "/debug.snapshot.diff",
      "/debug-snapshot-track",
      "/debug-snapshot-patch",
      "/debug-snapshot-diff",
    ],
    description: "Show BetterC0de snapshot/checkpoint diagnostics",
    category: "builtin",
    action: "execute",
  },
  {
    id: "debug-utility",
    name: "/debug-utility",
    aliases: [
      "/debug.startup",
      "/debug-startup",
      "/debug.scrap",
      "/debug-scrap",
      "/debug.v2",
      "/debug-v2",
      "/debug.wait",
      "/debug-wait",
    ],
    description: "Show BetterC0de startup/scrap/v2/wait debug guidance",
    category: "builtin",
    action: "execute",
  },
  {
    id: "stats",
    name: "/stats",
    aliases: ["/token-usage", "/session.stats", "/session-stats"],
    description: "Show BetterC0de token, model, and tool history",
    category: "builtin",
    action: "execute",
  },
  {
    id: "usage",
    name: "/usage",
    aliases: ["/cli-usage"],
    description: "Open live Claude, Codex, and Grok CLI usage",
    category: "builtin",
    action: "execute",
  },
  {
    id: "docs",
    name: "/docs",
    aliases: ["/documentation", "/docs.open", "/docs-open"],
    description: "Open BetterC0de documentation",
    category: "builtin",
    action: "execute",
  },
  {
    id: "settings",
    name: "/settings",
    aliases: ["/preferences", "/settings.open", "/settings-open"],
    description: "Open Settings, optionally with a tab name",
    category: "builtin",
    action: "execute",
  },
  {
    id: "remote",
    name: "/remote",
    aliases: ["/remote-access"],
    description:
      "Enable remote access and create a one-time phone/browser link",
    category: "builtin",
    action: "execute",
  },
  {
    id: "providers",
    name: "/providers",
    aliases: ["/model.dialog.provider", "/model-dialog-provider"],
    description: "Open provider settings",
    category: "builtin",
    action: "execute",
  },
  {
    id: "org",
    name: "/org",
    aliases: [
      "/organization",
      "/orgs",
      "/switch-org",
      "/console.orgs",
      "/console-orgs",
      "/console.switch",
      "/console-switch",
      "/console.org.switch",
      "/console-org-switch",
      "/account.orgs",
      "/account.switch",
    ],
    description: "Open or prefill provider account organization command",
    category: "builtin",
    action: "execute",
  },
  {
    id: "appearance",
    name: "/appearance",
    description: "Open appearance settings",
    category: "builtin",
    action: "execute",
  },
  {
    id: "rules",
    name: "/rules",
    description: "Open custom rules settings",
    category: "builtin",
    action: "execute",
  },
  {
    id: "instructions",
    name: "/instructions",
    aliases: ["/project-rules"],
    description: "Show or add BetterC0de instruction file globs",
    category: "builtin",
    action: "execute",
  },
  {
    id: "references",
    name: "/references",
    aliases: ["/refs", "/project-references"],
    description: "Show or write configured BetterC0de project references",
    category: "builtin",
    action: "execute",
  },
  {
    id: "formatters",
    name: "/formatters",
    aliases: ["/project-formatters", "/formatter.status", "/formatter-status"],
    description: "Show configured BetterC0de project formatters",
    category: "builtin",
    action: "execute",
  },
  {
    id: "format",
    name: "/format",
    aliases: ["/project-format", "/formatter.run"],
    description: "Run or preview a BetterC0de project formatter on a file",
    category: "builtin",
    action: "execute",
  },
  {
    id: "lsp",
    name: "/lsp",
    aliases: [
      "/lsps",
      "/language-servers",
      "/debug.lsp",
      "/debug-lsp",
      "/lsp.status",
      "/lsp-status",
      "/debug.lsp.diagnostics",
      "/debug-lsp-diagnostics",
      "/debug.lsp.symbols",
      "/debug-lsp-symbols",
      "/debug.lsp.document-symbols",
      "/debug-lsp-document-symbols",
    ],
    description:
      "Show configured BetterC0de LSP servers, diagnostics guidance, and JSON previews",
    category: "builtin",
    action: "execute",
  },
  {
    id: "permissions",
    name: "/permissions",
    aliases: ["/project-permissions"],
    description: "Show or write BetterC0de project permission rules",
    category: "builtin",
    action: "execute",
  },
  {
    id: "approvals",
    name: "/approvals",
    aliases: [
      "/approval-list",
      "/permission-list",
      "/permission.list",
      "/permissions-pending",
      "/permission.prompt.fullscreen",
      "/permission-fullscreen",
    ],
    description: "List pending provider approval requests",
    category: "builtin",
    action: "execute",
  },
  {
    id: "approve",
    name: "/approve",
    aliases: [
      "/approval-approve",
      "/permission-approve",
      "/permission.reply",
      "/permission.respond",
    ],
    description: "Approve a pending provider approval request",
    category: "builtin",
    action: "execute",
  },
  {
    id: "deny",
    name: "/deny",
    aliases: ["/reject", "/approval-deny", "/permission-deny"],
    description: "Deny a pending provider approval request",
    category: "builtin",
    action: "execute",
  },
  {
    id: "questions",
    name: "/questions",
    aliases: [
      "/question-list",
      "/question.list",
      "/user-inputs",
      "/user-input-list",
    ],
    description: "List pending provider question requests",
    category: "builtin",
    action: "execute",
  },
  {
    id: "answer",
    name: "/answer",
    aliases: ["/question-reply", "/question.reply", "/user-input-answer"],
    description: "Answer a pending provider question request",
    category: "builtin",
    action: "execute",
  },
  {
    id: "reject-question",
    name: "/reject-question",
    aliases: ["/question-reject", "/question.reject", "/user-input-reject"],
    description: "Reject a pending provider question request",
    category: "builtin",
    action: "execute",
  },
  {
    id: "todos",
    name: "/todos",
    aliases: ["/todo", "/tasks", "/session.todo"],
    description: "Show the current BetterC0de session todo list",
    category: "builtin",
    action: "execute",
  },
  {
    id: "vcs",
    name: "/vcs",
    aliases: [
      "/vcs-status",
      "/vcs.status",
      "/vcs.get",
      "/vcs-diff",
      "/vcs.diff",
      "/vcs-diff-raw",
      "/vcs.diff.raw",
      "/vcs-apply",
      "/vcs.apply",
    ],
    description: "Show BetterC0de VCS status, diff, or apply guidance",
    category: "builtin",
    action: "execute",
  },
  {
    id: "betterc0de",
    name: "/betterc0de-config",
    aliases: [
      "/betterc0de",
      "/compat-config",
      "/project-config",
      "/betterc0de",
      "/betterc0de-config",
      "/debug.config",
      "/debug-config",
      "/config.get",
      "/config-get",
      "/config.update",
      "/config-update",
      "/global.config.get",
      "/global-config-get",
      "/global.config.update",
      "/global-config-update",
    ],
    description: "Show BetterC0de project config summary or debug JSON preview",
    category: "builtin",
    action: "execute",
  },
  {
    id: "betterc0de-audit",
    name: "/betterc0de-audit",
    aliases: [
      "/betterc0de.parity",
      "/betterc0de-parity",
      "/compat",
      "/compat-audit",
      "/betterc0de.parity",
      "/betterc0de-parity",
      "/betterc0de-audit",
      "/parity",
    ],
    description: "Show BetterC0de compatibility coverage",
    category: "builtin",
    action: "execute",
  },
  {
    id: "betterc0de-cli",
    name: "/betterc0de-cli",
    aliases: [
      "/betterc0de.commands",
      "/betterc0de-commands",
      "/betterc0de.entrypoints",
      "/betterc0de-entrypoints",
      "/betterc0de.commands",
      "/betterc0de-commands",
      "/betterc0de.entrypoints",
      "/betterc0de-entrypoints",
      "/betterc0de-cli",
    ],
    description: "Show command-by-command BetterC0de compatibility coverage",
    category: "builtin",
    action: "execute",
  },
  {
    id: "betterc0de-http",
    name: "/betterc0de-api",
    aliases: [
      "/betterc0de.api",
      "/betterc0de-http",
      "/betterc0de.http",
      "/betterc0de.api",
      "/betterc0de-api",
      "/betterc0de.http",
      "/betterc0de-http",
      "/openapi",
      "/openapi.operations",
    ],
    description: "Show BetterC0de HTTP/API compatibility coverage",
    category: "builtin",
    action: "execute",
  },
  {
    id: "betterc0de-gaps",
    name: "/betterc0de-gaps",
    aliases: [
      "/betterc0de.missing",
      "/betterc0de-missing",
      "/betterc0de.todo",
      "/betterc0de-todo",
      "/betterc0de.missing",
      "/betterc0de-missing",
      "/betterc0de.todo",
      "/betterc0de-todo",
      "/betterc0de-gaps",
    ],
    description: "Show partial and display-only BetterC0de compatibility gaps",
    category: "builtin",
    action: "execute",
  },
  {
    id: "mcp-resources",
    name: "/mcp-resources",
    aliases: [
      "/resources",
      "/mcp.resources",
      "/mcp-resource-list",
      "/experimental.resource.list",
      "/experimental-resource-list",
    ],
    description: "Show BetterC0de MCP resource availability",
    category: "builtin",
    action: "execute",
  },
  {
    id: "betterc0de-sync",
    name: "/betterc0de-sync",
    aliases: [
      "/betterc0de.sync",
      "/betterc0de-sync",
      "/sync",
      "/sync.history.list",
      "/sync-history",
      "/sync.replay",
      "/sync-replay",
      "/sync.start",
      "/sync-start",
      "/sync.steal",
      "/sync-steal",
    ],
    description: "Show BetterC0de sync compatibility and validation",
    category: "builtin",
    action: "execute",
  },
  {
    id: "betterc0de-workspace",
    name: "/betterc0de-workspace",
    aliases: [
      "/betterc0de.workspace",
      "/betterc0de-workspace",
      "/experimental.workspace.syncList",
      "/experimental-workspace-sync-list",
      "/experimental.workspace.warp",
      "/experimental-workspace-warp",
    ],
    description: "Show BetterC0de workspace sync/warp compatibility",
    category: "builtin",
    action: "execute",
  },
  {
    id: "betterc0de-lifecycle",
    name: "/betterc0de-lifecycle",
    aliases: [
      "/betterc0de.lifecycle",
      "/betterc0de-lifecycle",
      "/global.dispose",
      "/global-dispose",
      "/instance.dispose",
      "/instance-dispose",
    ],
    description: "Show BetterC0de lifecycle compatibility",
    category: "builtin",
    action: "execute",
  },
  {
    id: "tui-control",
    name: "/tui-control",
    aliases: [
      "/tui.control.next",
      "/tui-control-next",
      "/tui.control.response",
      "/tui-control-response",
    ],
    description: "Show BetterC0de terminal control compatibility",
    category: "builtin",
    action: "execute",
  },
  {
    id: "betterc0de-internal",
    name: "/betterc0de-internal",
    aliases: [
      "/betterc0de.internal",
      "/betterc0de-internal",
      "/auth.set",
      "/auth-set",
      "/auth.remove",
      "/auth-remove",
      "/provider.oauth.authorize",
      "/provider.oauth.callback",
      "/experimental.console.get",
      "/experimental.console.listOrgs",
      "/experimental.console.switchOrg",
      "/experimental.session.list",
      "/experimental.workspace.adapter.list",
      "/experimental.workspace.create",
      "/experimental.workspace.list",
      "/experimental.workspace.remove",
      "/experimental.workspace.status",
      "/global.event",
      "/global.upgrade",
      "/part.delete",
      "/part.update",
      "/project.initGit",
      "/session.command",
      "/session.deleteMessage",
      "/session.prompt",
      "/session.prompt_async",
      "/session.shell",
      "/session.summarize",
      "/tui.appendPrompt",
      "/tui.clearPrompt",
      "/tui.executeCommand",
      "/tui.openHelp",
      "/tui.openModels",
      "/tui.openSessions",
      "/tui.openThemes",
      "/tui.publish",
      "/tui.selectSession",
      "/tui.showToast",
      "/tui.submitPrompt",
      "/v2.session.prompt",
      "/v2.session.wait",
    ],
    description: "Show BetterC0de handling for internal compatibility routes",
    category: "builtin",
    action: "execute",
  },
  {
    id: "tui",
    name: "/tui",
    aliases: ["/tui-config"],
    description: "Show or write BetterC0de terminal UI project config",
    category: "builtin",
    action: "execute",
  },
  {
    id: "keybinds",
    name: "/keybinds",
    aliases: [
      "/keybindings",
      "/which-key",
      "/which-key.toggle",
      "/which-key.layout.toggle",
      "/which-key.pending.toggle",
      "/which-key.group.previous",
      "/which-key.group.next",
      "/which-key.scroll.up",
      "/which-key.scroll.down",
      "/which-key.page.up",
      "/which-key.page.down",
      "/which-key.home",
      "/which-key.end",
    ],
    description: "Show or write BetterC0de terminal UI keybind overrides",
    category: "builtin",
    action: "execute",
  },
  {
    id: "tips",
    name: "/tips",
    aliases: ["/tips.toggle", "/betterc0de-tips", "/tips-toggle"],
    description: "Show BetterC0de workflow tips",
    category: "builtin",
    action: "execute",
  },
  {
    id: "attachments",
    name: "/attachments",
    aliases: ["/attachment", "/image-attachments", "/betterc0de-attachments"],
    description: "Show or write BetterC0de attachment limits",
    category: "builtin",
    action: "execute",
  },
  {
    id: "tool-output",
    name: "/tool-output",
    aliases: ["/tool-output-limits", "/betterc0de-tool-output"],
    description: "Show or write BetterC0de tool output truncation limits",
    category: "builtin",
    action: "execute",
  },
  {
    id: "compaction",
    name: "/compaction",
    aliases: ["/context-compaction", "/betterc0de-compaction"],
    description: "Show or write BetterC0de context compaction settings",
    category: "builtin",
    action: "execute",
  },
  {
    id: "betterc0de-runtime",
    name: "/betterc0de-runtime",
    aliases: [
      "/betterc0de.server",
      "/betterc0de-app",
      "/runtime-config",
      "/betterc0de-runtime",
      "/betterc0de-server",
      "/betterc0de-app",
    ],
    description:
      "Show BetterC0de runtime, server, limits, watcher, and app settings",
    category: "builtin",
    action: "execute",
  },
  {
    id: "betterc0de-tui",
    name: "/betterc0de-tui",
    aliases: [
      "/betterc0de.thread",
      "/betterc0de-thread",
      "/betterc0de.ui",
      "/betterc0de-ui",
      "/betterc0de-tui",
      "/betterc0de.thread",
      "/betterc0de-thread",
      "/betterc0de.ui",
      "/betterc0de-ui",
    ],
    description: "Show or prefill the default BetterC0de terminal command",
    category: "builtin",
    action: "execute",
  },
  {
    id: "betterc0de-run",
    name: "/betterc0de-run",
    aliases: [
      "/betterc0de.run",
      "/betterc0de-cli-run",
      "/betterc0de.run",
      "/betterc0de-cli-run",
      "/betterc0de-run",
    ],
    description: "Show or prefill BetterC0de run compatibility command",
    category: "builtin",
    action: "execute",
  },
  {
    id: "betterc0de-serve",
    name: "/betterc0de-serve",
    aliases: [
      "/betterc0de.serve",
      "/betterc0de-server-start",
      "/betterc0de.serve",
      "/betterc0de-server-start",
      "/betterc0de-serve",
    ],
    description:
      "Show or prefill BetterC0de headless server compatibility command",
    category: "builtin",
    action: "execute",
  },
  {
    id: "betterc0de-attach",
    name: "/betterc0de-attach",
    aliases: [
      "/betterc0de.attach",
      "/betterc0de-server-switch",
      "/betterc0de-attach",
      "/betterc0de.attach",
      "/attach",
      "/attach-server",
      "/server.switch",
      "/server-switch",
    ],
    description:
      "Show or prefill BetterC0de remote server attach compatibility command",
    category: "builtin",
    action: "execute",
  },
  {
    id: "betterc0de-web",
    name: "/betterc0de-web",
    aliases: [
      "/betterc0de.web",
      "/betterc0de-web-ui",
      "/betterc0de.web",
      "/betterc0de-web-ui",
      "/betterc0de-web",
    ],
    description: "Show or prefill BetterC0de web UI compatibility command",
    category: "builtin",
    action: "execute",
  },
  {
    id: "betterc0de-acp",
    name: "/betterc0de-acp",
    aliases: ["/betterc0de.acp", "/betterc0de.acp", "/betterc0de-acp", "/acp"],
    description: "Show or prefill BetterC0de ACP compatibility command",
    category: "builtin",
    action: "execute",
  },
  {
    id: "betterc0de-upgrade",
    name: "/betterc0de-upgrade",
    aliases: [
      "/betterc0de.upgrade",
      "/betterc0de-update",
      "/betterc0de.upgrade",
      "/betterc0de-update",
      "/betterc0de-upgrade",
    ],
    description: "Show or prefill BetterC0de upgrade compatibility command",
    category: "builtin",
    action: "execute",
  },
  {
    id: "betterc0de-uninstall",
    name: "/betterc0de-uninstall",
    aliases: [
      "/betterc0de.uninstall",
      "/betterc0de.uninstall",
      "/betterc0de-uninstall",
    ],
    description: "Show or prefill BetterC0de uninstall compatibility command",
    category: "builtin",
    action: "execute",
  },
  {
    id: "betterc0de-generate",
    name: "/betterc0de-generate",
    aliases: [
      "/betterc0de.generate",
      "/betterc0de-openapi",
      "/betterc0de.generate",
      "/betterc0de-openapi",
      "/betterc0de-generate",
    ],
    description:
      "Show or prefill BetterC0de API generation compatibility command",
    category: "builtin",
    action: "execute",
  },
  {
    id: "betterc0de-completion",
    name: "/betterc0de-completion",
    aliases: [
      "/betterc0de.completion",
      "/betterc0de.completion",
      "/betterc0de-completion",
      "/completion",
    ],
    description:
      "Show or prefill BetterC0de shell completion compatibility command",
    category: "builtin",
    action: "execute",
  },
  {
    id: "betterc0de-db",
    name: "/betterc0de-db",
    aliases: [
      "/betterc0de.db",
      "/betterc0de-db-path",
      "/betterc0de-db-migrate",
      "/betterc0de-db",
      "/betterc0de.db",
      "/betterc0de-db-path",
      "/betterc0de-db-migrate",
      "/db",
      "/db.migrate",
      "/db-query",
    ],
    description: "Show or prefill BetterC0de database compatibility command",
    category: "builtin",
    action: "execute",
  },
  {
    id: "project-providers",
    name: "/project-providers",
    aliases: [
      "/provider-config",
      "/betterc0de-providers",
      "/config.providers",
      "/config-providers",
      "/v2.provider.list",
      "/v2-provider-list",
      "/v2.provider.get",
      "/v2-provider-get",
    ],
    description: "Show BetterC0de project provider config",
    category: "builtin",
    action: "execute",
  },
  {
    id: "project-plugins",
    name: "/project-plugins",
    aliases: ["/betterc0de-plugins"],
    description: "Show BetterC0de project plugin config",
    category: "builtin",
    action: "execute",
  },
  {
    id: "project-tools",
    name: "/project-tools",
    aliases: [
      "/betterc0de-tools",
      "/tool.list",
      "/tool-list",
      "/tool.ids",
      "/tool-ids",
    ],
    description: "Show or write BetterC0de project tool flags",
    category: "builtin",
    action: "execute",
  },
  {
    id: "tools",
    name: "/tools",
    aliases: ["/mcp-settings"],
    description: "Open tools and MCP settings",
    category: "builtin",
    action: "execute",
  },
  {
    id: "hooks",
    name: "/hooks",
    description: "Open hooks and automation settings",
    category: "builtin",
    action: "execute",
  },
  {
    id: "plugins",
    name: "/plugins",
    aliases: ["/plugins.list", "/plugins-list"],
    description: "Open plugin settings",
    category: "builtin",
    action: "execute",
  },
  {
    id: "plugin-toggle",
    name: "/plugin-toggle",
    aliases: ["/plugins.toggle", "/plugins-toggle"],
    description:
      "Set BetterC0de terminal UI plugin enablement in project config",
    category: "builtin",
    action: "execute",
  },
  {
    id: "plugin-install",
    name: "/plugin-install",
    aliases: [
      "/plugin",
      "/plug",
      "/plugin.install",
      "/plugins.install",
      "/plugins-install",
      "/dialog.plugins.install",
      "/dialog-plugins-install",
    ],
    description: "Show or add a BetterC0de plugin config entry",
    category: "builtin",
    action: "execute",
  },
  {
    id: "console",
    name: "/console",
    aliases: ["/app.console", "/app-console", "/app.debug", "/app-debug"],
    description: "Toggle the BetterC0de console/debug panel",
    category: "builtin",
    action: "execute",
  },
  {
    id: "app-log",
    name: "/app.log",
    aliases: ["/app-log"],
    description: "Write a BetterC0de log entry to the local console",
    category: "builtin",
    action: "execute",
  },
  {
    id: "heap-snapshot",
    name: "/heap-snapshot",
    aliases: ["/app.heap_snapshot", "/app-heap-snapshot"],
    description: "Write a Node backend heap snapshot",
    category: "builtin",
    action: "execute",
  },
  {
    id: "terminal",
    name: "/terminal",
    aliases: [
      "/terminal.toggle",
      "/terminal.suspend",
      "/pty",
      "/pty.list",
      "/pty-list",
      "/pty.shells",
      "/pty-shells",
      "/pty.get",
      "/pty-get",
      "/pty.connect",
      "/pty-connect",
      "/pty.connectToken",
      "/pty.connect-token",
      "/pty.remove",
      "/pty-remove",
    ],
    description: "Toggle the terminal panel",
    category: "builtin",
    action: "execute",
  },
  {
    id: "terminal-title",
    name: "/terminal-title",
    aliases: [
      "/terminal.title.toggle",
      "/terminal-title-toggle",
      "/pty.update",
    ],
    description: "Toggle integrated terminal tab titles",
    category: "builtin",
    action: "execute",
  },
  {
    id: "terminal-new",
    name: "/terminal-new",
    aliases: ["/terminal.new", "/new-terminal", "/pty.create", "/pty-create"],
    description: "Open a new terminal session",
    category: "builtin",
    action: "execute",
  },
  {
    id: "sidebar",
    name: "/sidebar",
    aliases: ["/toggle-sidebar", "/sidebar.toggle", "/session.sidebar.toggle"],
    description: "Toggle the main app sidebar",
    category: "builtin",
    action: "execute",
  },
  {
    id: "animations",
    name: "/animations",
    aliases: ["/app.toggle.animations", "/app-toggle-animations"],
    description: "Toggle UI animations",
    category: "builtin",
    action: "execute",
  },
  {
    id: "file-context",
    name: "/file-context",
    aliases: ["/app.toggle.file_context", "/app-toggle-file-context"],
    description: "Toggle file-context prompt features",
    category: "builtin",
    action: "execute",
  },
  {
    id: "paste-summary",
    name: "/paste-summary",
    aliases: ["/app.toggle.paste_summary", "/app-toggle-paste-summary"],
    description: "Pasted text stays editable (legacy command)",
    category: "builtin",
    action: "execute",
  },
  {
    id: "session-directory-filter",
    name: "/session-directory-filter",
    aliases: [
      "/app.toggle.session_directory_filter",
      "/app-toggle-session-directory-filter",
    ],
    description: "Toggle workspace-aware session filtering",
    category: "builtin",
    action: "execute",
  },
  {
    id: "connect",
    name: "/connect",
    aliases: [
      "/provider.connect",
      "/provider-connect",
      "/providers.login",
      "/provider.login",
      "/auth.login",
      "/auth.connect",
      "/console.login",
      "/console.open",
      "/account.login",
      "/account.open",
    ],
    description: "Show or prefill provider connection command",
    category: "builtin",
    action: "execute",
  },
  {
    id: "auth",
    name: "/auth",
    aliases: [
      "/auth.list",
      "/auth.ls",
      "/auth.get",
      "/provider-auth",
      "/provider.auth",
      "/providers.list",
      "/providers.ls",
      "/provider.list",
      "/provider.ls",
      "/providers.logout",
      "/provider.logout",
      "/auth.logout",
      "/console.logout",
      "/account",
      "/account.list",
      "/account.logout",
    ],
    description: "Show or prefill provider authentication command",
    category: "builtin",
    action: "execute",
  },
  {
    id: "themes",
    name: "/themes",
    aliases: [
      "/theme",
      "/theme.switch",
      "/theme-switch",
      "/theme.cycle",
      "/theme-cycle",
      "/theme.scheme.cycle",
      "/theme-scheme-cycle",
    ],
    description: "List or switch available themes",
    category: "builtin",
    action: "execute",
  },
  {
    id: "theme-mode",
    name: "/theme-mode",
    aliases: ["/theme.switch_mode", "/theme-switch-mode"],
    description: "Switch between light and dark theme mode",
    category: "builtin",
    action: "execute",
  },
  {
    id: "theme-mode-lock",
    name: "/theme-mode-lock",
    aliases: ["/theme.mode.lock", "/theme-lock"],
    description: "Lock or unlock the current theme mode",
    category: "builtin",
    action: "execute",
  },
  {
    id: "language",
    name: "/language",
    aliases: ["/language.cycle", "/language-cycle"],
    description: "Show BetterC0de language command compatibility",
    category: "builtin",
    action: "execute",
  },
  {
    id: "terminal-font",
    name: "/terminal-font",
    aliases: ["/font.terminal", "/terminal.font", "/appearance.terminal_font"],
    description: "Show or set the integrated terminal font",
    category: "builtin",
    action: "execute",
  },
  {
    id: "variants",
    name: "/variants",
    aliases: ["/variant.list", "/variant-list"],
    description: "Show model variant support for this provider",
    category: "builtin",
    action: "execute",
  },
  {
    id: "variant-cycle",
    name: "/variant.cycle",
    aliases: ["/variant-cycle", "/model.variant.cycle", "/model-variant-cycle"],
    description: "Cycle the current BetterC0de model variant",
    category: "builtin",
    action: "execute",
  },
  {
    id: "catalog",
    name: "/catalog",
    aliases: [
      "/model-catalog",
      "/model-info",
      "/models.list",
      "/models-list",
      "/catalog.model.list",
      "/catalog.model.get",
    ],
    description: "Inspect provider model catalog metadata",
    category: "builtin",
    action: "execute",
  },
  {
    id: "streaming",
    name: "/streaming",
    description: "Toggle assistant response streaming",
    category: "builtin",
    action: "execute",
  },
  {
    id: "timestamps",
    name: "/timestamps",
    aliases: [
      "/toggle-timestamps",
      "/toggle.timestamps",
      "/session.toggle.timestamps",
    ],
    description: "Toggle chat message timestamps",
    category: "builtin",
    action: "execute",
  },
  {
    id: "thinking",
    name: "/thinking",
    aliases: [
      "/toggle-thinking",
      "/toggle.thinking",
      "/session.toggle.thinking",
    ],
    description: "Toggle assistant thinking blocks",
    category: "builtin",
    action: "execute",
  },
  {
    id: "reasoning-summaries",
    name: "/reasoning-summaries",
    aliases: [
      "/reasoning-summary",
      "/session.toggle.reasoning_summaries",
      "/session-toggle-reasoning-summaries",
    ],
    description: "Toggle compact reasoning summary headings",
    category: "builtin",
    action: "execute",
  },
  {
    id: "tool-details",
    name: "/tool-details",
    aliases: [
      "/actions",
      "/toggle-actions",
      "/toggle.actions",
      "/session.toggle.actions",
    ],
    description: "Toggle expanded tool details in chat",
    category: "builtin",
    action: "execute",
  },
  {
    id: "session-progress",
    name: "/progress",
    aliases: [
      "/session-progress",
      "/session.toggle.progress_bar",
      "/session-toggle-progress-bar",
    ],
    description: "Toggle BetterC0de session progress rows",
    category: "builtin",
    action: "execute",
  },
  {
    id: "shell-expanded",
    name: "/shell-expanded",
    aliases: [
      "/shell-tool-parts",
      "/shell-tool-parts-expanded",
      "/session.toggle.shell_tool_parts_expanded",
    ],
    description: "Toggle default expansion for shell tool parts",
    category: "builtin",
    action: "execute",
  },
  {
    id: "edit-expanded",
    name: "/edit-expanded",
    aliases: [
      "/edit-tool-parts",
      "/edit-tool-parts-expanded",
      "/session.toggle.edit_tool_parts_expanded",
    ],
    description: "Toggle default expansion for edit/write/patch tool parts",
    category: "builtin",
    action: "execute",
  },
  {
    id: "scrollbar",
    name: "/scrollbar",
    aliases: [
      "/toggle-scrollbar",
      "/toggle.scrollbar",
      "/session.toggle.scrollbar",
    ],
    description: "Toggle the main chat scrollbar",
    category: "builtin",
    action: "execute",
  },
  {
    id: "generic-tool-output",
    name: "/generic-tool-output",
    aliases: [
      "/generic-output",
      "/toggle-generic-tool-output",
      "/toggle.generic_tool_output",
      "/session.toggle.generic_tool_output",
    ],
    description: "Toggle raw output previews for generic tools",
    category: "builtin",
    action: "execute",
  },
  {
    id: "conceal",
    name: "/conceal",
    aliases: ["/toggle-conceal", "/session.toggle.conceal"],
    description: "Toggle concealed code block previews in chat",
    category: "builtin",
    action: "execute",
  },
  {
    id: "autosave",
    name: "/autosave",
    aliases: ["/auto-save"],
    description: "Toggle automatic conversation saving",
    category: "builtin",
    action: "execute",
  },
  {
    id: "diffwrap",
    name: "/diffwrap",
    aliases: ["/wrap", "/app.toggle.diffwrap", "/app-toggle-diffwrap"],
    description: "Toggle diff viewer word wrap",
    category: "builtin",
    action: "execute",
  },
  {
    id: "diff-style",
    name: "/diff-style",
    aliases: ["/diff_style", "/diff.style", "/app.diff_style"],
    description: "Set BetterC0de diff layout auto or stacked",
    category: "builtin",
    action: "execute",
  },
  {
    id: "confirmations",
    name: "/confirmations",
    aliases: ["/confirm"],
    description: "Toggle archive and delete confirmations",
    category: "builtin",
    action: "execute",
  },
  {
    id: "notifications",
    name: "/notifications",
    aliases: ["/notify", "/notification"],
    description: "Show or change native notification settings",
    category: "builtin",
    action: "execute",
  },
  {
    id: "autoaccept",
    name: "/autoaccept",
    aliases: ["/auto-accept", "/permissions.autoaccept"],
    description: "Toggle automatic tool approval for this chat",
    category: "builtin",
    action: "execute",
  },
  {
    id: "compact",
    name: "/compact",
    aliases: [
      "/summarize",
      "/session.compact",
      "/v2.session.compact",
      "/v2-session-compact",
    ],
    description: "Compact the current chat into a thread summary",
    category: "builtin",
    action: "execute",
  },
  {
    id: "density",
    name: "/density",
    aliases: ["/compact-ui"],
    description: "Toggle compact chat spacing",
    category: "builtin",
    action: "execute",
  },
]

const BUILTIN_COMMAND_NAMES = new Set(
  BUILTIN_COMMANDS.flatMap((command) => [
    command.name,
    ...(command.aliases ?? []),
  ]).map(normalizeCommandToken)
)

export function filterBuiltinCommandsForBetterC0deShareMode(
  commands: ReadonlyArray<SlashCommand>,
  shareMode: BetterC0deShareMode | null
): SlashCommand[] {
  if (shareMode !== "disabled") return [...commands]
  return commands.filter(
    (command) => command.id !== "share" && command.id !== "unshare"
  )
}

export function isReservedBuiltinSlashCommandName(name: string): boolean {
  return BUILTIN_COMMAND_NAMES.has(normalizeCommandToken(name))
}

function normalizeCommandToken(value: string): string {
  return value.trim().replace(/^\/+/, "").toLowerCase()
}
